### PR TITLE
Version 2.4.4

### PR DESCRIPTION
**Pull request by Sunoo**
### Changes

- Added support for unbridging specific cameras.This can aid with performance of the camera and Homebridge as a whole, but requires manually adding any unbridged cameras to HomeKit.

### CODE REVIEW

**Comment by gondalez** [comment]
Hi, would you mind explaining how it slows down the whole instance? 
I appreciate the perf improvements but am considering if enabling this option will improve responsiveness for me. 

Thanks for the plugin :)

**Comment by Sunoo** [comment]
Certainly. The way bridges work in HomeKit only allows one device on the bridge to be communicating at a time. So if, for example, the bridge is currently dealing with getting a snapshot for a camera, nothing else on the bridge can update during that time. Watching live video from the cameras works differently and doesn’t take up the entire bridge.

This was most apparent to users who had multiple cameras, some were reporting taking a minute or more to finally get updated snapshots from them.

**Comment by gondalez** [comment]
Interesting, thank you for the explanation. I will give it a try - I have three cams and do notice small delay with snapshots from time to time.

**Comment by Sunoo** [comment]
Under ideal conditions, the Home app will request a new snapshot every 10 seconds. It's slower on cellular, but I don't remember what cadence it uses there. If you're seeing more than 10-11 seconds on wifi though, it's probably because your Homebridge instance is being clogged up. Or I suppose your camera could be really slow to provide a still.

**Comment by gondalez** [comment]
Ah cool yes, now that you mention it I can see the delay within the home app.  

I have three cameras and when I view home it loads one at a time. In the end the "seconds ago" display ends up being out of sync for them. They are wired cameras so load pretty quick.

If I move to unbridged I should expect to see them stay mostly in sync.
It's not the biggest problem but I think it'll be interesting to try out (and secretly pleasing if the times remain sync'd).
I have a hunch this will be more noticeable on the watch app which has the same issue.

PS I believe the cadence is 60 secs on cellular.

Thanks again for the discussion :)

**Pull request merged**
