### PR TITLE
Added ability to specify the pixel format that is to be used

### PR DESCRIPTION
**Pull request by beele**
Keeps yuv420p as the default if the option is not provided in the config

### CODE REVIEW

**Comment by Sunoo** [comment]
Is there a need for this? I’d assume that iOS devices would always be expecting the same pixel format?

**Comment by donavanbecker** [comment]
@beele also if @Sunoo did merge this, you would also want to add this to the `config.schema.json`

**Comment by Sunoo** [comment]
Yea, the config.schema is easy enough to fix, I was just wondering if there is a need for this feature.

I’m assuming Beele saw some scenario where it is needed, I just want to understand what. If some devices don’t like yuv420p, perhaps the better approach would be to change the default, but I’ve never seen a device choke on that yet.

**Comment by beele** [comment]
@Sunoo I was going over the code from Unifi Protect 2 and came across this: https://github.com/hjdhjd/homebridge-unifi-protect2/blob/772c6401f2923f950a50d5363b8a428c5b795a1a/src/protect-stream.ts#L247
Where it states that the one being used in this plugin is deprecated. I though it might be handy to have the option to specify it.
I'm by no means an expert in pixel formats, so if this is unnecessary feel free to reject the PR ;)

**Comment by Sunoo** [comment]
Interesting, I’ll do some testing after work today, but that sounds like it may be more appropriate to just change what I used as opposed to making it configurable. This plugin exposes a ton of options already, and I’m reluctant to pile more on without a good reason, especially a setting like this where users are unlikely to know what the setting does.

**Comment by Sunoo** [comment]
I pulled up the FFmpeg source, and the only deprecation I can find is the pixel format yuvj420p: http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavutil/pixfmt.h;hb=HEAD#l78

In fact, I’ve found many references to yuv420p being the most common and most compatible format, and it seems to be the only format handled by some hardware acceleration.

I took a look at the code you linked, and according to the comment, @hjdhjd moved from yuvj420p to yuvj422p, but both of those formats are deprecated according to the FFmpeg source.

**Comment by Sunoo** [comment]
@hjdhjd I did find a few forum threads mentioning yuv420p being deprecated, but I’m pretty sure the posters confused it with yuvj420p. As bad as FFmpeg’s docs are, they do seem to recommend yuv420p in a few places, and mention it as the default for a few settings.

**Comment by beele** [comment]
@Sunoo I see, then there's no need for this PR ;) I'll close it!

**Comment by Sunoo** [comment]
Sounds good. Thanks anyways!

**Pull request closed without merging**
