### PR TITLE
Update tested configurations for the Raspberry Pi camera module

### PR DESCRIPTION
**Pull request by moritzmhmk**
I am the developer of [homebridge-camera-rpi](https://github.com/moritzmhmk/homebridge-camera-rpi) and while developing support for multiple streams I found that using this plugin and contributing configurations makes more sense.

While looking at the existing tested configurations for the Pi I found some redundancy and decided to refactor those.

For the older Pi models (especially the Pi zero) using the native h264 makes sense but has some downsides. If there is interest in enhancing this project to support the required features (i.e. access to the requested resolution and framerate in the source argument - possibly by replacing defined tokens and custom flip and rotate commands) to fix those downsides let me know and I will open a dedicated PR for that. Ideally this would render my plugin obsolete.

### CODE REVIEW

**Comment by Sunoo** [comment]
Could you provide a bit more information on what would be needed to fully support the Pi camera? I don't have access to one of the camera modules, so I don't have any direct experience with them. Does FFmpeg not grab the correct resolution and framerate using V4L2 for this, which works for every other webcam I've tested? Also, do video filters not work correctly on this camera, which is the typical way of handling flip and rotation.

**Comment by moritzmhmk** [comment]
In combination with a Raspberry Pi 2 or newer the configuration I provided with this PR using the gpu accelerated h264_omx encoder works fine and flip etc. can be done with video filters. Also using the configuration for multiple streams works nicely with this newer boards.


The Raspberry Pi zero (which is used because of its small physical size) only has a single core cpu running at 1Ghz (the older B+ models at 700Mhz). These boards do not work that well even with the gpu accelerated encoder since it still causes too much cpu load. Using the capability of the camera to output h264 directly (probably also handled by the gpu but with less load on the cpu for some reason) gives more reliable results with nicer image quality. 

Using the h264 from the camera requires one to use the copy "encoder" and as such to not apply any filters (which would cause too much cpu load anyway). This stops one from using the common methods of handling flip and rotation. These can be handled by setting them for the camera via `4l2-ctl`. This can either be handled by the plugin with an extra option or be handled by a systemd service created independently from the plugin.

Setting the correct resolution and framerate needs to be done when those information are given in the request and as such can't be handled by the config or a startup script.
The configuration in this PR just sets them to 720p and ignores the requested resolution (again no video filters etc. with copy "encoder"). A nice solution would be to adjust the source on every request filling in the requested resolution and framerate.
Example: ``"source": "-f video4linux2 -input_format h264 -video_size $WIDTHx$HEIGHT -framerate $FPS -timestamps abs -i /dev/video0"``
The plugin would just replace $WIDTH etc. with the currently requested values. The replacement could be triggered by an additional argument to avoid replacing $WIDTH when it might actually be part of a valid source argument for some camera.

The bitrate can't be set by ffmpeg (see [ticket](https://trac.ffmpeg.org/ticket/6639)). The command to set the bitrate is `v4l2-ctl --set-ctrl video_bitrate=300000`. One might just set this to a reasonable value like 300k and ignore the requested bitrate but it would certainly be nicer if this command was executed on every request.

My homebridge-camera-rpi plugin handles the above by calling `v4l2-ctl` on startup to set rotation and flip as defined in the configuration as well as on every request to set the bitrate. It also includes the requested resolution in the ffmpeg command.

The perfect solution would provide
* a way to use the requested resolution, fps etc. in the source option by using a primitive template language as suggested above (ideally with an option to disable this)
* an option `use_v4l2_ctl` that causes the plugin to set flip, rotation and bitrate using `v4l2_ctl`. Since flip and rotation are now part of the video filter option we need to either parse that option or provide that information to the newly created  option (i.e. passing an object with hflip, vflip and rotation keys to `use_v4l2_ctl`). This should work for any camera with a v4l2 driver.

**Comment by Sunoo** [comment]
I’m giving myself a little bit of a break from coding this long weekend, but this does seem like something that might be worth implementing, especially given that it would be generic to any v4l2 camera, not just the Pi camera.

I really want to avoid adding too many more settings to the config, it’s already a sea of confusing options for users, and I’d ideally like to simplify it from what even exists currently. I’m also slightly reluctant to add settings that only work on Linux, when this supports Windows and Mac as well.

I’m certain there is a reasonable way of handling this though, I’d just have to give it some thought.

**Comment by moritzmhmk** [comment]
Can we merge this and open a separate PR or Issue for the proposed additions for v4l2-ctl support?

**Comment by moritzmhmk** [comment]
any update on this? :)

**Comment by m-rossi** [comment]
I would recommend to merge @Sunoo, I am using @moritzmhmk configuration in this PR since a few weeks and they work just fine, thanks!

**Pull request closed without merging**
